// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyAL5pxTzAyF5RIRkrDGL0u03ijF9piG0',
    appId: '1:398288303465:web:6fe1d5f8192f4a613379f8',
    messagingSenderId: '398288303465',
    projectId: 'hafizprogram-17672',
    authDomain: 'hafizprogram-17672.firebaseapp.com',
    storageBucket: 'hafizprogram-17672.appspot.com',
    measurementId: 'G-273F49ENKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLNV-VraE7HBIyk0k_iAhTeTSJAQ5dBBg',
    appId: '1:398288303465:android:93edc19140829c6b3379f8',
    messagingSenderId: '398288303465',
    projectId: 'hafizprogram-17672',
    storageBucket: 'hafizprogram-17672.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD71FbOU3oSNphQWZXQYeAEn4KBc8V7rd0',
    appId: '1:398288303465:ios:c2242cc2e88e59263379f8',
    messagingSenderId: '398288303465',
    projectId: 'hafizprogram-17672',
    storageBucket: 'hafizprogram-17672.appspot.com',
    iosClientId: '398288303465-0nsgt55tb0po249ibtchovb52kb42etl.apps.googleusercontent.com',
    iosBundleId: 'com.example.hafizProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD71FbOU3oSNphQWZXQYeAEn4KBc8V7rd0',
    appId: '1:398288303465:ios:c2242cc2e88e59263379f8',
    messagingSenderId: '398288303465',
    projectId: 'hafizprogram-17672',
    storageBucket: 'hafizprogram-17672.appspot.com',
    iosClientId: '398288303465-0nsgt55tb0po249ibtchovb52kb42etl.apps.googleusercontent.com',
    iosBundleId: 'com.example.hafizProje',
  );
}
